name: Docker Publish

on:
  workflow_run:
    workflows : ["Docker build"]
    branches: ["master"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get short sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/qlever:${{ if github.ref_name == 'master' && steps.sha.outputs.sha_short || github.ref_name }},
            ${{ secrets.DOCKERHUB_USERNAME }}/qlever:latest

