name: Docker Publish

on:
  workflow_run:
    workflows : ["docker-build"]
    branches: ["main"]
    types:
      - completed
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: >
            ${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }},
            ${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref }},
            ${{ github.repository_owner }}/${{ github.repository }}:latest

